### ISSUE TITLE
Definir perfiles de usuario

### ISSUE THREAD

**Issue by Torchu** [Torchu/flixbuff#1]
Clarificar los perfiles de las distintas personas a las que va dirigido el trabajo. De ésta forma, se podrán definir y tratar de resolver los distintos problemas que puedan tener.

Recoger esta información en la memoria del proyecto.

**Comment by JJ** [comment]
"Como programador" realmente no sería una HU, sino simplemente un issue. Este issue estaría relacionado con la HU en la que hables del tribunal.
