### ISSUE TITLE
Eliminar capítulo de descripción

### ISSUE THREAD

**Issue by Torchu** [Torchu/flixbuff#15]
El capítulo 2 según la plantilla, no se va a realizar. Sería conveniente eliminarlo y renombrar el resto de capítulos acorde.

**Comment by JJ** [comment]
¿Por qué razón? Los issues son siempre problemas, no tareas. ¿Qué problema representa ese capítulo? ¿Dentro de qué historia de usuario está ese problema?

**Comment by Torchu** [comment]
La razón es que ese capítulo venía de la plantilla, pero no va a ser realizado y queremos mantener una memoria limpia para el tribunal como se declara en #8
