### ISSUE TITLE
Los apéndices no están incluidos en la comprobación ortográfica

### ISSUE THREAD

**Issue by JJ** [Torchu/flixbuff#17]
También puedes usar `find` para que salgan todos los ficheros en vez de varios bucles. O un glob un poco más genérico (`*/*.tex`)

https://github.com/Torchu/flixbuff/blob/916281ac52114d58d76e40b3cc966b46e70218b2/scripts/spellcheck.sh#L28

**Comment by Torchu** [comment]
Depende de https://github.com/Torchu/flixbuff/pull/12
