### ISSUE TITLE
Definir los objetivos del proyecto

### ISSUE THREAD

**Issue by Torchu** [Torchu/flixbuff#3]
Una vez definido el problema a resolver, se deben plantear una serie de objetivos específicos, medibles y alcanzables.

**Comment by JJ** [comment]
Igualmente, simplemente un issue. Las HUs son siempre descripciones de anhelos o deseos de los usuarios, no las tareas que vas a hacer para eso. Y en este caso, igualmente sería principalmente para el tribunal, pero en general para todo el mundo.
