### ISSUE TITLE
[HU04] Como usuario quiero dar mi opinión sobre las temporadas de las series que veo para socializar

### ISSUE THREAD

**Issue by Torchu** [Torchu/flixbuff#36]
- [x] Cada temporada se comentará de forma individual.
- [x] La opinión debe ir acompañada de una puntuación del 0 al 10.

**Comment by Torchu** [comment]
¿Qué implica la opinión?

**Comment by Torchu** [comment]
> ¿Qué implica la opinión?

La opinión incluye un texto de reseña acompañado por una puntuación del 0 al 10.

**Comment by JJ** [comment]
> Se cambia series por temporadas de las series. Ya que las series son un conjunto de distintas temporadas, como usuario quiero poder comentar cada una de ellas de forma individual.

¿Por qué dejas el cuerpo del HU vacío y lo pones esto aquí?

**Comment by Torchu** [comment]
> > Se cambia series por temporadas de las series. Ya que las series son un conjunto de distintas temporadas, como usuario quiero poder comentar cada una de ellas de forma individual.
> 
> ¿Por qué dejas el cuerpo del HU vacío y lo pones esto aquí?

Como era un añadido a posteriori pensé que quedaría mejor como un comentario nuevo. Refleja mejor el cambio, pero vaya, de primeras lo había puesto en el cuerpo, lo pongo ahí también.
