### ISSUE TITLE
Modelizar la entidad reseña

### ISSUE THREAD

**Issue by Torchu** [Torchu/flixbuff#51]
Modelizar la entidad reseña mencionada en #36.
Las reseñas se realizarán a nivel de temporada.
Una reseña debe contener:
- Nombre del autor.
- Datos de la temporada:
  - Nombre de la serie.
  - Número de la temporada.
  - Nombre de la temporada.
- El texto de la reseña.
- Una puntuación entre 0 y 10, ambos incluidos.

**Comment by JJ** [comment]
Estás planteando la implementación directamente, no el problema. Así planteado, no cabe discusión posible, ni se puede implementar más que lo que aquí dice.

La forma como tendrías que plantear esto es partiendo de #36 y yendo a productos mínimamente viables. "Quiero dar mi opinión" no incluye puntuación, por ejemplo. "Sobre las series" no incluye temporadas. "la serie" implica un identificador único, no el nombre de la serie.

El desarrollo ágil implica que se haga lo que pida el cliente, *y sólo lo que pida el cliente*, avanzando hacia productos mínimamente viables, es decir, no inventando nada. Si crees que lo que comentas aquí como solución es adecuado, tienes varias opciones: cambiar #36 para incluirlo o simplemente hacer una nueva HU que incluya ese tipo de cosas.

También puedes iniciar un diálogo en #36 , aunque sea contigo mismo. ¿Opinión incluye puntuación, o sólo "mola" o "apesta"?

En cualquier caso, lo que quiere el usuario es algo que tiene que aparecer de forma lo menos ambigua posible en la HU, y los problemas que esto plantea deben aparecer en los issues correspondientes. Los issues nunca deben incluir directamente la implementación; esta sólo debe estar en el código.

**Comment by Torchu** [comment]
Estoy de acuerdo en lo de la puntuación y lo de las temporadas.

Lo de plantearlo yendo a productos mínimamente viables no sé a qué te refieres. He esquematizado lo que debería incluir el modelo según la información que extraigo de la HU. La idea era tener una issue definiendo los requisitos de aceptación del PR que lo resuelva. No se me ocurre una forma mejor de hacer eso, pero estoy abierto a ideas.

Lo de que en los datos de la temporada no se incluya el nombre de la serie y sí un identificador único... Tanto el nombre de la serie como el de la temporada están porque el usuario querrá ver esos datos en la reseña. No entiendo por qué no ponerlos. Lo del identificador único sigo pensando que eso viene con la persistencia de los datos. Quizá use una base de datos que use un hash como identificador o alguna combinación alfanumérica o quizá use una tabla excel y el identificador sea el número de fila en la que se ubican los datos, por eso no estoy poniendo identificadores en este milestone.

**Comment by JJ** [comment]
Significa que tienes que usar lo mínimo que cuente como "opinión" para ti.
Una frase, o un "me gusta" o "no me gusta"

La idea del desarrollo ágil es que el cliente dice "quiero expresar mi
opinión". Tú le dices "Vale, aquí tienes: me gusta o no". El cliente dice:
"Vale, pero yo quiero añadir algo más, una frase o dos" o "No, yo quiero
puntuarlo de 0 a 10". Eso se incorpora al desarrollo en un milestone
siguiente, con su HU correspondiente.

Una "frase" más una puntuación de 0 a 10 no es de ninguna forma mínimo. De
la misma forma podíamos decir "Título de reseña, dos párrafos y 1 a 5
estrellas"

**Comment by Torchu** [comment]
Entonces lo de la puntuación lo dejo como estaba y lo creo como un issue para el siguiente milestone?

**Comment by JJ** [comment]
Es una cuestión simplemente de lenguaje y de lo que el cliente diga que necesita, que en este caso es lo que a ti te dé la gana. Simplemente con que añadas "opinión *cuantificada*" ya se ve necesaria la calificación. La cuestión no es lo que decidas o no puntualmente sobre una HU, sino que lo que hagas para desarrollar la HU sea sólo y exclusivamente lo que en la HU dice que necesita; eso es el concepto de mínimo.

**Comment by Torchu** [comment]
Vale, la HU #36 ya incluye lo de las temporadas y las series, pero sigo sin ver por qué está mal hecho el acceptance criteria de este issue. ¿Cuál sería el formato a seguir? No entiendo cómo deberían estar las cosas y esto me está bloqueando bastante, yo solo quiero empezar a programar :(

**Comment by Torchu** [comment]
Al modificar la HU y este mismo issue en concordancia, estoy viendo bastante inutil el issue #52 que creé. ¿Qué opinas? ¿Lo cierro?

**Comment by JJ** [comment]
> Al modificar la HU y este mismo issue en concordancia, estoy viendo bastante inutil el issue #52 que creé. ¿Qué opinas? ¿Lo cierro?

Esas decisiones tienen que ser siempre tuyas, claro. Recuerda la regla de cerrar con un commit siempre; puede ser un texto donde expliques cómo estás haciendo la modelización del dominio y demás.

En cuanto a la videollamada, como tú veas; a partir de mañana mejor.

**Comment by Torchu** [comment]
Pues dime hora para mañana. A mi me da igual, podría escaparme un poco del trabajo para ello. Mientras no sea de 10:00 a 10:30, no debería tener más reuniones.

**Comment by JJ** [comment]
Dame un toque por Telegram cuando estés listo, por la mañana en principio tengo igual una reunión a las 10, pero puede que salga.
